apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: xvp-infra-core-app-of-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sivakumark88/guestbook.git
    targetRevision: HEAD
    path: apps/guestbook
    helm:
      values: |
        continent: na
        environment: plat-dev
        region: us-east-2
      valuesFiles:
#        - values.yaml
        - plat-dev-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
