apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: xvp-infra-core-app-of-apps
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/sivakumark88/guestbook.git
      targetRevision: HEAD
      path: apps/guestbook
      helm:
        values: |
          environment: plat-dev
          continent: na
          region: us-east-2
        valuesFiles:
          - values.yaml
          # - values/plat-dev-values.yaml
          # - $xvpInfraCore/nfra/gitops/app-guestbook/values/values.yaml
          # - $xvpInfraCore/nfra/gitops/app-guestbook/values/plat-dev-values.yaml
          # # - $xvpInfraCore/infra/gitops/app-guestbook/plat-dev-values.yaml
          # # - '$xvpInfraCore/infra/gitops/app-guestbook/${environment}-${continent}-values.yaml'
          # # - '$xvpInfraCore/infra/gitops/app-guestbook/${environment}-${region}-values.yaml'
    - repoURL: https://github.com/sivakumark88/guestbook.git
      targetRevision: HEAD
      ref: xvp
  destination:
    server: https://kubernetes.default.svc
    namespace: guestbook
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
